name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run action
        uses: ./
        with:
          app-name: Test App Name

      - name: Check project
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.'* ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi

      - name: Run action with CLI version
        uses: ./
        with:
          cli-version: 2.8.4

      - name: Check project
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.8.4' ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi
