name: test
on: [push, pull_request]

permissions:
  contents: read

env:
  TAURI_CONF: src-tauri/tauri.conf.json

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create web assets
        shell: bash
        run: |
          mkdir -p dist
          echo '<h1>Test App</h1>' > dist/index.html

      - name: Run action
        uses: ./
        with:
          app-name: Test App Name

      - name: Assert outputs
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.'* ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi

          if [[
            "$(jq -r .productName $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r '.app.windows[0].title' $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r .identifier $TAURI_CONF)" != 'com.remarkablemark.tauri-action'
            && "$(jq -r .build.frontendDist $TAURI_CONF)" != '../dist'
            && "$(jq -r .build.beforeBuildCommand $TAURI_CONF)" != 'exit 0'
          ]]; then
            echo 'Tauri configuration does not match. See JSON below:'
            cat $TAURI_CONF
            exit 1
          fi

          ls src-tauri/target/release/bundle/*

      - name: Run action with inputs
        id: tauri
        uses: ./
        with:
          app-name: Test App Name
          app-version: 1.2.3
          window-title: Test Window Title
          window-width: 1024
          window-height: 768
          tauri-path: .
          frontend-dist: ../dist
          before-build-command: echo test
          force: true
          identifier: org.remarkablemark.test
          tauri-version: 2.9.0
        env:
          # https://tauri.app/distribute/sign/macos/#ad-hoc-signing
          APPLE_SIGNING_IDENTITY: '-'

      - name: Assert outputs
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.9.0' ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi

          if [[
            "$(jq -r .productName $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r .version $TAURI_CONF)" != '1.2.3'
            && "$(jq -r '.app.windows[0].title' $TAURI_CONF)" != 'Test Window Title'
            && "$(jq -r '.app.windows[0].width' $TAURI_CONF)" != '1024'
            && "$(jq -r '.app.windows[0].height' $TAURI_CONF)" != '768'
            && "$(jq -r .identifier $TAURI_CONF)" != 'org.remarkablemark.test'
            && "$(jq -r .build.frontendDist $TAURI_CONF)" != '../dist'
            && "$(jq -r .build.beforeBuildCommand $TAURI_CONF)" != 'echo test'
          ]]; then
            echo 'Tauri configuration does not match. See JSON below:'
            cat $TAURI_CONF
            exit 1
          fi

          if [[ "${{ steps.tauri.outputs.bundle-path }}" != *'src-tauri/target/release/bundle' ]]; then
            echo 'Tauri bundle path does not match. See below:'
            ls src-tauri/target/release/bundle/*
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.os }}
          path: ${{ steps.tauri.outputs.bundle-path }}
