name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run action
        uses: ./
        with:
          app-name: Test App Name

      - name: Check project
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.'* ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi

          TAURI_CONF=src-tauri/tauri.conf.json

          if [[
            "$(jq -r .productName $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r '.app.windows[0].title' $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r .build.frontendDist $TAURI_CONF)" != '../dist'
            && "$(jq -r .build.beforeBuildCommand $TAURI_CONF)" != 'exit 0'
          ]]; then
            echo 'Tauri configuration does not match. See JSON below:'
            cat TAURI_CONF
            exit 1
          fi

      - name: Run action with inputs
        uses: ./
        with:
          app-name: Test App Name
          window-title: Test Window Title
          tauri-path: .
          frontend-dist: ../build
          before-build-command: npm run build
          force: true
          cli-version: 2.8.4

      - name: Check project
        shell: bash
        run: |
          if [[ "$(tauri --version)" != 'tauri-cli 2.8.4' ]]; then
            echo 'Version does not match. See version below:'
            tauri --version
            exit 1
          fi

          TAURI_CONF=src-tauri/tauri.conf.json

          if [[
            "$(jq -r .productName $TAURI_CONF)" != 'Test App Name'
            && "$(jq -r '.app.windows[0].title' $TAURI_CONF)" != 'Test Window Title'
            && "$(jq -r .build.frontendDist $TAURI_CONF)" != '../build'
            && "$(jq -r .build.beforeBuildCommand $TAURI_CONF)" != 'npm run build'
          ]]; then
            echo 'Tauri configuration does not match. See JSON below:'
            cat TAURI_CONF
            exit 1
          fi
